// Copyright (c) 2010-2022 The Open-Transactions developers
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#pragma once

#include <limits>
#include <type_traits>

#include "opentxs/blockchain/Types.hpp"  // IWYU pragma: keep

namespace opentxs::blockchain
{
enum class Type : std::underlying_type_t<Type> {
    UnknownBlockchain = 0,
    Bitcoin = 1,
    Bitcoin_testnet3 = 2,
    BitcoinCash = 3,
    BitcoinCash_testnet3 = 4,
    Ethereum = 5,
    Ethereum_frontier = Ethereum,
    Ethereum_homestead = Ethereum,
    Ethereum_metropolis = Ethereum,
    Ethereum_ropsten = 6,
    Litecoin = 7,
    Litecoin_testnet4 = 8,
    PKT = 9,
    PKT_testnet = 10,
    BitcoinSV = 11,
    BitcoinSV_testnet3 = 12,
    eCash = 13,
    eCash_testnet3 = 14,
    Casper = 15,
    Casper_testnet = 16,
    BitcoinCash_testnet4 = 17,
    Dash = 18,
    Dash_testnet3 = 19,
    Ethereum_goerli = 20,
    Ethereum_sepolia = 21,
    Ethereum_holesovice = 22,
    Algorand = 23,
    Arweave = 24,
    Avalanche = 25,
    BinanceChain = 26,
    BinanceSmartChain = 27,
    BitShares = 28,
    BitcoinGold = 29,
    Cardano = 30,
    Celo = 31,
    Chiliz = 32,
    Cosmos = 33,
    Decred = 34,
    Dogecoin = 35,
    Dogecoin_testnet = 36,
    EOS = 37,
    Elrond = 38,
    EthereumClassic = 39,
    Ethereum_kovan = 40,
    Ethereum_morden = 41,
    Ethereum_olympic = 42,
    Ethereum_rinkeby = 43,
    Expance = 44,
    Factom = 45,
    Fantom = 46,
    Filecoin = 47,
    Flow = 48,
    Harmony = 49,
    Hedera = 50,
    Helium = 51,
    Huobi = 52,
    ICON = 53,
    IOTA = 54,
    InternetComputer = 55,
    Kadena = 56,
    Klaytn = 57,
    Kusama = 58,
    MaidSafeCoin = 59,
    MaidSafeCoin_testnet = 60,
    Mina = 61,
    Monero = 62,
    Monero_testnet = 63,
    Near = 64,
    NEM = 65,
    NEM_testnet = 66,
    Neo = 67,
    Nxt = 68,
    Nxt_testnet = 69,
    OKB = 70,
    POA = 71,
    POA_sokol = 72,
    Polkadot = 73,
    Polygon = 74,
    Qtum = 75,
    Quant = 76,
    Ravencoin = 77,
    Ripple = 78,
    Ripple_testnet = 79,
    Secret = 80,
    Siacoin = 81,
    Siacoin_testnet = 82,
    Solana = 83,
    Stacks = 84,
    Steem = 85,
    Steem_testnet = 86,
    Stellar = 87,
    THETA = 88,
    THORChain = 89,
    Terra = 90,
    Tezos = 91,
    ThetaFuel = 92,
    Tron = 93,
    VeChain = 94,
    Waves = 95,
    Waves_testnet = 96,
    XDC = 97,
    Zcash = 98,
    Zilliqa = 99,
    UnitTest = std::numeric_limits<int>::max(),
};
}  // namespace opentxs::blockchain
