version: 2.1

parameters:
  docker-image-tag:
    default: "14"
    type: string

executors:
  host_executor:
    machine:
      image: ubuntu-2004:current
      
commands:
  prepare_env:
    description: "command to prepare all build dependencies: code deps, gems, tools"
    parameters:
      arch:
        type: string
    steps:
      #pulling docker image is somehow much slower than using docker image as executor
      #pulling        : 2m 44s
      #docker executor: 1m 40s
      - run:
          name: "pull docker image"
          command: docker pull opentransactions/android:<<pipeline.parameters.docker-image-tag>>
      #TODO check if that does anything at all (ssh into running image)
      - run:
          name: "get more disk space"
          command: |
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /usr/share/dotnet
      - checkout
      - run:
          name: "checkout submodules (circleci doesn't do that by default)"
          working_directory: "~/project"
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: "prepare temp dirs"
          working_directory: "~/"
          command: |
            mkdir -p opentxs-for-android/<<parameters.arch>>

jobs:
  build-android:
    parameters:
      arch:
        type: string
    executor: host_executor
    steps:
      - prepare_env:
          arch: <<parameters.arch>>
      - run:
          name: "build"
          command: |
            docker run --mount type=bind,src=/home/circleci/project,dst=/home/src --mount type=bind,src=/home/circleci/opentxs-for-android/<<parameters.arch>>,dst=/home/output -i opentransactions/android:14 <<parameters.arch>> all

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-opentxs-android:
    jobs:
      - build-android:
          matrix:
            parameters:
              arch: [arm64, arm, x64, x86]
              

