version: 2.1

parameters:
  docker-image-android-tag:
    default: "14"
    type: string
  docker-image-ci-tag:
    default: "8"
    type: string

executors:
  host_executor:
    machine:
      image: ubuntu-2004:current
      
commands:
  prepare_env:
    description: "command to prepare all build dependencies: code deps, gems, tools"
    parameters:
      docker-image:
        type: string
      temp-path:
        type: string
    steps:
      #pulling docker image is somehow much slower than using docker image as executor
      #pulling        : 2m 44s
      #docker executor: 1m 40s
      - run:
          name: "pull docker image"
          command: docker pull <<parameters.docker-image>>
      #TODO check if that does anything at all (ssh into running image)
      - run:
          name: "get more disk space"
          command: |
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /usr/share/dotnet
      - checkout
      - run:
          name: "checkout submodules (circleci doesn't do that by default)"
          working_directory: "~/project"
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: "prepare temp dirs"
          working_directory: "~/"
          command: |
            mkdir -p <<parameters.temp-path>>

jobs:
  build-android:
    parameters:
      arch:
        type: string
    executor: host_executor
    steps:
      - prepare_env:
          docker-image: opentransactions/android:<<pipeline.parameters.docker-image-android-tag>>
          temp-path: opentxs-for-android/<<parameters.arch>>
      - run:
          name: "build"
          command: |
            docker run --mount type=bind,src=/home/circleci/project,dst=/home/src --mount type=bind,src=/home/circleci/opentxs-for-android/<<parameters.arch>>,dst=/home/output -i opentransactions/android:<<pipeline.parameters.docker-image-android-tag>> <<parameters.arch>> all
  build-linux:
    parameters:
      command:
        type: string
      mode:
        type: string
    executor: host_executor
    steps:
      - prepare_env:
          docker-image: opentransactions/ci:<<pipeline.parameters.docker-image-ci-tag>>
          temp-path: "/tmp/opentxs"
      - run:
          name: "build"
          command: |
            docker run --mount type=bind,src=/home/circleci/project,dst=/home/src --mount type=bind,src=/tmp/opentxs,dst=/home/output -i --entrypoint /usr/bin/build-opentxs-<<parameters.command>> opentransactions/ci:<<pipeline.parameters.docker-image-ci-tag>> <<parameters.mode>> 

workflows:
  build-opentxs-android:
    jobs:
      - build-android:
          matrix:
            parameters:
              arch: [arm64, arm, x64, x86]
  build-opentxs-linux:
    jobs:
      - build-linux:
          matrix:
            parameters:
              command: [gcc, clang]
              mode: [test01, test02, test03, test04, test05, test06, test07, test08, nopch, full]