version: 2.1

parameters:
  docker-image-tag:
    default: "14"
    type: string
  #https://discuss.circleci.com/t/circleci-orb-with-array-parameters-and-for-loop/36964/2
  architectures:
    default: "arm64 arm x64 x86"
    type: string

executors:
  host_executor:
    machine:
      image: ubuntu-2004:current
      
commands:
  prepare_env:
    description: "command to prepare all build dependencies: code deps, gems, tools"
    steps:
      #pulling docker image is somehow much slower than using docker image as executor
      #pulling        : 2m 44s
      #docker executor: 1m 40s
      - run:
          name: "pull docker image"
          command: docker pull opentransactions/android:<<pipeline.parameters.docker-image-tag>>
      #TODO check if that does anything at all (ssh into running image)
      - run:
          name: "get more disk space"
          command: |
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /usr/share/dotnet
      - checkout
      - run:
          name: "checkout submodules, circleci doesn't do that by default"
          working_directory: "~/project"
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: "prepare temp dirs"
          working_directory: "~/"
          command: |
            for i in <<pipeline.parameters.architectures>>; do
              mkdir -p opentxs-for-android/$i
            done

jobs:
  build-android-arm64:
    executor: host_executor
    steps:
      - prepare_env
      - run:
          name: "build arm64"
          command: |
            docker run --mount type=bind,src=/home/circleci/project,dst=/home/src --mount type=bind,src=/home/circleci/opentxs-for-android/arm64,dst=/home/output -i opentransactions/android:14 arm64 all
  build-android-arm:
    executor: host_executor
    steps:
      - prepare_env
      - run:
          name: "build arm"
          command: |
            docker run --mount type=bind,src=/home/circleci/project,dst=/home/src --mount type=bind,src=/home/circleci/opentxs-for-android/arm64,dst=/home/output -i opentransactions/android:14 arm all
  build-android-x64:
    executor: host_executor
    steps:
      - prepare_env
      - run:
          name: "build x64"
          command: |
            docker run --mount type=bind,src=/home/circleci/project,dst=/home/src --mount type=bind,src=/home/circleci/opentxs-for-android/arm64,dst=/home/output -i opentransactions/android:14 x64 all
  build-android-x86:
    executor: host_executor
    steps:
      - prepare_env
      - run:
          name: "build x86"
          command: |
            docker run --mount type=bind,src=/home/circleci/project,dst=/home/src --mount type=bind,src=/home/circleci/opentxs-for-android/arm64,dst=/home/output -i opentransactions/android:14 x86 all

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-opentxs-android:
    jobs:
      - build-android-arm64
      - build-android-arm
      - build-android-x64
      - build-android-x86

