name: Android

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        binding: [all]
        arch: [arm64, arm, x64, x86]
        include:
          - binding: all
            platform: ubuntu-20.04
            docker: 21
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout opentxs
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    - name: Setup build environment
      run: |
        docker pull opentransactions/android:${{ matrix.docker }}
    - name:  Get more disk space
      run:   |
             if [ "$RUNNER_OS" == "Linux" ]; then
                  sudo rm -rf /usr/lib/mono
                  sudo rm -rf /usr/local/lib/android
                  sudo rm -rf /usr/local/share/vcpkg
                  sudo rm -rf /usr/share/miniconda
             elif [ "$RUNNER_OS" == "macOS" ]; then
                  sudo rm -rf "/Library/Frameworks/Mono.framework"
                  sudo rm -rf "/Users/runner/Library/Android"
                  sudo rm -rf "/usr/local/miniconda"
                  sudo rm -rf "/usr/local/share/vcpkg"
             elif [ "$RUNNER_OS" == "Windows" ]; then
                  rm -rf "C:\Android"
                  rm -rf "C:\Miniconda"
                  rm -rf "C:\Program Files\dotnet"
                  rm -rf "C:\SeleniumWebDrivers\"
                  rm -rf "C:\selenium\"
                  rm -rf "C:\vcpkg"
             fi
      shell: bash
    - name: Compile
      run: |
        mkdir -p ${{ runner.temp }}/opentxs-for-android/${{ matrix.arch }}
        docker run --mount type=bind,src=${{ github.workspace }},dst=/home/src --mount type=bind,src=${{ runner.temp }}/opentxs-for-android/${{ matrix.arch }},dst=/home/output -i opentransactions/android:${{ matrix.docker }} ${{ matrix.arch }} ${{ matrix.binding }}
#    - uses: actions/upload-artifact@v2
#      with:
#        name: ${{ matrix.arch }}-${{ matrix.binding }}
#        path: ${{ runner.temp }}/opentxs-for-android/${{ matrix.arch }}
#        if-no-files-found: error
#  package:
#    needs: build
#    strategy:
#      matrix:
#        binding: [qt]
#    runs-on: ubuntu-20.04
#    steps:
#    - run: |
#        mkdir -p ${{ runner.temp }}/opentxs-for-android/
#    - uses: actions/download-artifact@v2
#      with:
#        name: arm64-${{ matrix.binding }}
#        path: ${{ runner.temp }}/opentxs-for-android/arm64
#    - uses: actions/download-artifact@v2
#      with:
#        name: arm64-${{ matrix.binding }}
#        path: ${{ runner.temp }}/opentxs-for-android/arm
#    - uses: actions/download-artifact@v2
#      with:
#        name: arm64-${{ matrix.binding }}
#        path: ${{ runner.temp }}/opentxs-for-android/x64
#    - uses: actions/download-artifact@v2
#      with:
#        name: arm64-${{ matrix.binding }}
#        path: ${{ runner.temp }}/opentxs-for-android/x86
#    - name: Package artifacts
#      run: |
#        cd ${{ runner.temp }}
#        zip -r opentxs-for-android.zip opentxs-for-android/
#    - uses: actions/upload-artifact@v2
#      with:
#        name: opentxs-for-android_${{ matrix.binding }}
#        path: ${{ runner.temp }}/opentxs-for-android.zip
#    - uses: geekyeggo/delete-artifact@v1
#      with:
#        name: |
#          arm64-${{ matrix.binding }}
#          arm-${{ matrix.binding }}
#          x64-${{ matrix.binding }}
#          x86-${{ matrix.binding }}
