name: Docker

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc-10.3, gcc-11.3, gcc-12.2, clang-12, clang-13, clang-14]
        # TODO "prod" configuration requires more ram than is available in the Github Actions runner
        mode: [test01, test02, test03, test04, test05, test06, test07, test08, nopch, full]
        include:
          - compiler: gcc-10.3
            command: /usr/bin/build-opentxs-gcc
            docker: 11
          - compiler: gcc-11.3
            command: /usr/bin/build-opentxs-gcc
            docker: 35_0
          - compiler: gcc-12.2
            command: /usr/bin/build-opentxs-gcc
            docker: 36_0
          - compiler: clang-12
            command: /usr/bin/build-opentxs-clang
            docker: 34_0
          - compiler: clang-13
            command: /usr/bin/build-opentxs-clang
            docker: 35_0
          - compiler: clang-14
            command: /usr/bin/build-opentxs-clang
            docker: 36_0
          - compiler: clang-tidy-14
            mode: tidy
            command: /usr/bin/build-opentxs-clang
            docker: 36_0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    - name: Get more disk space
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
    - name: Setup build environment
      run: |
        docker pull opentransactions/ci:${{ matrix.docker }}
    - name: Compile
      run: |
        mkdir -p /tmp/opentxs
        docker run --mount type=bind,src=${{ github.workspace }},dst=/home/src --mount type=bind,src=/tmp/opentxs,dst=/home/output -i --entrypoint ${{ matrix.command }} opentransactions/ci:${{ matrix.docker }} ${{ matrix.mode }}
#    - name: Run unit tests
#      run: |
#        mkdir -p /tmp/opentxs
#        docker run --tmpfs /tmp/build:rw,nosuid,size=2g --mount type=bind,src=${{ github.workspace }},dst=/home/src --mount type=bind,src=/tmp/opentxs,dst=/home/output -i opentransactions/ci:${{ matrix.docker }} /usr/bin/test-opentxs 2
