name: format

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  format:
    name: clang-format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      docker: '38_4'
    steps:
    - name: Checkout opentxs
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    - name: Get more disk space
      run: |
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "${JAVA_HOME_8_X64}"
        sudo rm -rf "${JAVA_HOME_11_X64}"
      shell: bash
      continue-on-error: true
    - name: Setup build environment
      run: |
        docker pull opentransactions/ci:${{ env.docker }}
    - name: Check formatting
      run: |
        mkdir -p /tmp/opentxs
        docker run --mount type=bind,src=${{ github.workspace }},dst=/home/src -i --entrypoint /usr/bin/check-formatting.sh opentransactions/ci:${{ env.docker }}
