name: format

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  format:
    name: clang-format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      docker: '38_6'
    steps:
    - name: Checkout opentxs
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    - name: Setup build environment
      run: |
        docker pull opentransactions/ci:${{ env.docker }}
    - name: Check formatting
      run: |
        mkdir -p /tmp/opentxs
        docker run --read-only --mount type=bind,src=${{ github.workspace }},dst=/home/src -i --entrypoint /usr/bin/check-formatting.sh opentransactions/ci:${{ env.docker }} /home/src
