name: linux

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  compile:
    name: ${{ matrix.toolchain }}-${{ matrix.preset }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gcc-12.2, gcc-13.0, gcc-13.2, clang-16, clang-17]
        preset: [test01, test02, test03, test04, test05, test06, test07, test08, nopch, full, notbb, release, matterfi]
        include:
          - toolchain: gcc-12.2
            docker: 37_10
            compiler: gcc
          - toolchain: gcc-13.0
            docker: 38_7
            compiler: gcc
          - toolchain: gcc-13.2
            docker: 39_1
            compiler: gcc
          - toolchain: clang-16
            docker: 38_7
            compiler: clang
          - toolchain: clang-17
            docker: 39_1
            compiler: clang
    steps:
    - name: Checkout opentxs
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    - name: Get more disk space
      run: |
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "${JAVA_HOME_8_X64}"
        sudo rm -rf "${JAVA_HOME_11_X64}"
      shell: bash
      continue-on-error: true
    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.3.6
      with:
        key: docker-ci-${{ matrix.docker }}
    - name: Setup build environment
      run: |
        docker pull opentransactions/ci:${{ matrix.docker }}
    - name: Compile
      run: |
        mkdir -p /tmp/opentxs
        docker run --mount type=bind,src=${{ github.workspace }},dst=/usr/src/ --mount type=bind,src=/tmp/opentxs,dst=/home/output -i opentransactions/ci:${{ matrix.docker }} /usr/src/ ${{ matrix.compiler }} ${{ matrix.preset }}
