name: tidy

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tidy:
    name: clang-tidy
    runs-on: ubuntu-22.04-large64
    strategy:
      fail-fast: true
    env:
      docker: '39_3'
      compiler: clang
      preset: tidy
    steps:
    - name: Checkout opentxs
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.3.6
      with:
        key: docker-ci-${{ matrix.docker }}
    - name: Setup build environment
      run: |
        docker pull opentransactions/ci:${{ env.docker }}
    - name: Compile
      run: |
        mkdir -p /tmp/opentxs
        docker run --mount type=bind,src=${{ github.workspace }},dst=/usr/src/ --mount type=bind,src=/tmp/opentxs,dst=/home/output -i opentransactions/ci:${{ env.docker }} /usr/src/ ${{ env.compiler }} ${{ env.preset }}
