name: tidy

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tidy:
    name: clang-tidy
    runs-on: ubuntu-22.04-large64
    strategy:
      fail-fast: true
    env:
      docker: '38_4'
      compiler: clang
      preset: tidy
    steps:
    - name: Checkout opentxs
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    - name: Setup build environment
      run: |
        docker pull opentransactions/ci:${{ env.docker }}
    - name: Compile
      run: |
        mkdir -p /tmp/opentxs
        docker run --mount type=bind,src=${{ github.workspace }},dst=/home/src --mount type=bind,src=/tmp/opentxs,dst=/home/output -i opentransactions/ci:${{ env.docker }} ${{ env.compiler }} ${{ env.preset }}
