name: vcpkg

on: [push, pull_request]

jobs:
  job:
    name: ${{ matrix.platform }}-${{ github.workflow }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-12, windows-2022]
        include:
          - platform: macos-12
            vcpkg_installed_repo: 'https://gitlab.com/opentxs-artifacts/vcpkg.git/'
            vcpkg_installed_root: '/Users/runner/work/opentxs/opentxs/deps/vcpkg_installed'
            preset: macos
            static_deps: 'ON'
            triplet: 'x64-osx-11'
          - platform: windows-2022
            vcpkg_installed_repo: 'https://gitlab.com/open-transactions/vcpkg.git/'
            vcpkg_installed_root: 'c:\vcpkg_installed'
            preset: msvc
            static_deps: 'OFF'
            triplet: 'x64-windows'
    env:
      VCPKG_INSTALLED_DIR: '${{ matrix.vcpkg_installed_root }}/${{ matrix.platform }}'
      VCPKG_OVERLAY_TRIPLETS: '${{ github.workspace }}/deps/vcpkg-overlay/triplets'
      VCPKG_DEFAULT_TRIPLET: '${{ matrix.triplet }}'
    steps:
    - name: Get more disk space
      run:  |
        rm -rvf '${GOROOT_1_17_X64}'
        rm -rvf '${GOROOT_1_18_X64}'
        rm -rvf '${GOROOT_1_19_X64}'
        rm -rvf '${JAVA_HOME_11_X64}'
        rm -rvf '${JAVA_HOME_13_X64}'
        rm -rvf '${JAVA_HOME_17_X64}'
        rm -rvf '${JAVA_HOME_8_X64}'
        rm -rvf '/Users/runner/Library/Android'
        rm -rvf 'C:\Android'
        rm -rvf 'C:\Microsoft\AndroidSDK'
        rm -rvf 'C:\Microsoft\AndroidNDK64'
        rm -rvf 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools'
        rm -rvf 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools'
        rm -rvf 'C:\Program Files\Google\Chrome'
        rm -rvf 'C:\Program Files\MongoDB'
        rm -rvf 'C:\Program Files\Mozilla Firefox'
        rm -rvf 'C:\Program Files\dotnet'
        rm -rvf 'C:\ProgramData\docker'
        rm -rvf 'C:\SeleniumWebDrivers'
        rm -rvf 'C:\selenium'
        rm -rvf 'C:\tools\Apache24'
        rm -rvf 'C:\tools\nginx-1.23.1'
        rm -rvf 'C:\vcpkg'
        rm -rvf /usr/bin/link'
      shell: bash
      continue-on-error: true
    - name: Checkout opentxs
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    - name: Checkout vcpkg_installed
      run: |
        git clone --depth=1 --single-branch --branch='${{ matrix.platform }}' '${{ matrix.vcpkg_installed_repo }}' '${{ matrix.vcpkg_installed_root }}'
      shell: bash
    - name: "Set VCPKG_ROOT"
      shell: bash
      run: |
        echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
    - name: Configure build environment
      uses: ilammy/msvc-dev-cmd@v1
    - name: Update cmake
      uses: lukka/get-cmake@latest
    - name: 'Compile'
      run: |
        cd '${{ github.workspace }}'
        cmake -S '${{ github.workspace }}' --preset '${{ matrix.preset }}' -DVCPKG_INSTALLED_DIR='${{ env.VCPKG_INSTALLED_DIR }}' -DVCPKG_TARGET_TRIPLET='${{ matrix.triplet }}' -DOT_STATIC_DEPENDENCIES='${{ matrix.static_deps }}' -DVCPKG_MANIFEST_MODE=OFF
        cmake --build --preset '${{ matrix.preset }}' -- -k 0
